---
- name: Install development headers
  apt: pkg="libpq-dev"
  become: true
  when: pg_dev_headers
  tags:
    - postgresql

- name: Install PostgreSQL contribs
  apt: pkg="postgresql-contrib-{{ pg_version }}"
  become: true
  when: pg_contrib
  tags:
    - postgresql
